name: Release Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DRTMIDI_API_JACK=OFF -DRTMIDI_BUILD_TESTING=OFF -DRTMIDI_BUILD_SHARED_LIBS=OFF

    - name: Build
      run: cmake --build ./build --config Release

    - name: Create Artifact
      run: |
        mkdir release
        cp build/line release/line

    # if: matrix.os == 'macos-latest' 
    - name: Publish macOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: line macOS release
        path: release

    # if: matrix.os == 'ubuntu-latest'
    # - name: Publish linux Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: line linux release
    #     path: release

  # release_linux:
  #   name: line linux release
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Checkout submodules
  #   run: git submodule update --init --recursive

  #   - name: Create Build Directory
  #     run: cmake -E make_directory ${{github.workspace}}/build

  #   - name: Configure CMake
  #     run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DRTMIDI_API_JACK=OFF -DRTMIDI_BUILD_TESTING=OFF -DRTMIDI_BUILD_SHARED_LIBS=OFF

  #   - name: Build
  #     run: cmake --build ./build --config Release

  #   - name: Create Artifact
  #     run: |
  #       mkdir release
  #       cp build/line release/line
    
  #   - name: Publish Linux Artifact
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: line linux release
  #       path: release

# Artifac creation not working
# release_windows:
#   name: windows cppandaction release
#   runs-on: windows-latest

#   steps:
#     - uses: actions/checkout@v2

#     - name: Create Build Directory
#       run: cmake -E make_directory ${{github.workspace}}/build

#     - name: Configure CMake
#       run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

#     - name: Build
#       run: cmake --build ./build --config Release

#     - name: Create Artifact
#       run: |
#         mkdir release
#         copy build/main.exe release/main.exe
    
#     - name: Publish Windows Artifact
#       uses: actions/upload-artifact@v2
#       with:
#         name: cppandaction windows release
#         path: release
# Artifac creation not working --      
